/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询梗图列表 */
        get: operations["MemesController_findAll"];
        put?: never;
        /** 新增梗图 */
        post: operations["MemesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询单个梗图 */
        get: operations["MemesController_findOne"];
        put?: never;
        post?: never;
        /** 删除梗图 */
        delete: operations["MemesController_remove"];
        options?: never;
        head?: never;
        /** 修改梗图文字信息 */
        patch: operations["MemesController_update"];
        trace?: never;
    };
    "/memes/{id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重新分析梗图 */
        post: operations["AiController_analyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateMemeDto: {
            /** @example /uploads/memes/example.png */
            imageUrl?: string;
            /** @example 程序员加班 */
            title?: string;
            /** @example 用于描述这张梗图 */
            description?: string;
            /**
             * @example [
             *       "程序员",
             *       "加班"
             *     ]
             */
            tags?: string[];
        };
        /** @enum {string} */
        MemeStatus: "PROCESSING" | "COMPLETED" | "FAILED";
        MemeResponseDto: {
            /** @example cmry37yj80000vznobcdlan7m */
            id: string;
            /** @example /uploads/memes/example.png */
            imageUrl: string;
            /**
             * @default
             * @example 程序员加班
             */
            title: string;
            /**
             * @default
             * @example 用于描述这张梗图
             */
            description: string;
            /**
             * @example [
             *       "程序员",
             *       "加班"
             *     ]
             */
            tags: string[];
            /**
             * @default
             * @example
             */
            ocrText: string;
            /** @example COMPLETED */
            status: components["schemas"]["MemeStatus"];
            /** @example null */
            errorMessage: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MemeListResponseDto: {
            items: components["schemas"]["MemeResponseDto"][];
            /** @example 20 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            pageSize: number;
        };
        UpdateMemeDto: {
            /** @example 程序员加班更新 */
            title?: string;
            /** @example 更新后的描述 */
            description?: string;
            /**
             * @example [
             *       "程序员",
             *       "工作"
             *     ]
             */
            tags?: string[];
        };
        AnalyzeMemeDto: {
            /** @example gpt-4o */
            model?: string;
            /**
             * @example [
             *       "猫",
             *       "动物",
             *       "吐槽"
             *     ]
             */
            recommendedTags?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MemesController_findAll: {
        parameters: {
            query?: {
                /** @description 搜索标题、描述或 OCR 文本 */
                q?: string;
                status?: components["schemas"]["MemeStatus"];
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemeListResponseDto"];
                };
            };
        };
    };
    MemesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file?: string;
                    /** @example /uploads/memes/example.png */
                    imageUrl?: string;
                    title?: string;
                    description?: string;
                    tags?: string[];
                };
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                    /** @example /uploads/memes/example.png */
                    imageUrl?: string;
                    title?: string;
                    description?: string;
                    tags?: string[];
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemeResponseDto"];
                };
            };
        };
    };
    MemesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 梗图 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemeResponseDto"];
                };
            };
            /** @description 梗图不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MemesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 梗图 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemeResponseDto"];
                };
            };
            /** @description 梗图不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MemesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 梗图 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemeResponseDto"];
                };
            };
            /** @description 梗图不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AiController_analyze: {
        parameters: {
            query?: never;
            header: {
                /** @description 当前本地会话使用的 AI API Key，不会保存到数据库 */
                "x-ai-api-key": string;
            };
            path: {
                /** @description 梗图 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeMemeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemeResponseDto"];
                };
            };
            /** @description 梗图不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
